color: null
fieldLayouts:
  84b1d8c7-974a-4039-babc-9e8cb8b5d838:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-18T03:07:12+00:00'
            elementCondition: null
            fieldUid: 7a94b27c-2786-43db-bd7d-e7a5883b52d1 # workスライド画像02
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01de0b68-7515-4b76-a034-be874b652d94
            userCondition: null
            warning: null
            width: 100
        name: コンテンツ
        uid: cb8edc6e-d4a9-4aee-bf64-9499ae1b62b3
        userCondition: null
handle: contentSlideImages02
hasTitleField: false
icon: null
name: スライド画像02
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
