color: null
fieldLayouts:
  482cd17a-6bfb-4030-a9ec-5d4efc7aa674:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-18T05:22:43+00:00'
            elementCondition: null
            fieldUid: 3172e165-5a99-41e4-876f-6b03fa7dbbf1 # worksコンテンツ画像１枚
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40236e76-0b57-4872-9713-a653ef4d83f0
            userCondition: null
            warning: null
            width: 100
        name: コンテンツ
        uid: 06f4c958-74d4-4161-8bc2-3e1e3221b887
        userCondition: null
handle: worksContentsImage
hasTitleField: false
icon: null
name: worksコンテンツ画像１枚
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
