color: null
fieldLayouts:
  8062995d-d52f-4390-9061-dd5ea0a08a8d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-18T05:26:11+00:00'
            elementCondition: null
            fieldUid: 83eb390c-c35e-461d-98ba-7f956701ba81 # worksスライド画像
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca1c4dce-e911-4aac-87c4-acef202d13cc
            userCondition: null
            warning: null
            width: 100
        name: スライド
        uid: fc94f871-54d4-48c6-baa6-0af12e068862
        userCondition: null
handle: worksSlideImages
hasTitleField: false
icon: null
name: worksスライド画像
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
