columnSuffix: null
handle: worksUrl
instructions: null
name: worksリンク
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - '1'
            -
              - allowAnchors
              - ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
