columnSuffix: null
handle: worksContents
instructions: null
name: worksコンテンツ
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 13bc13f8-c9b4-42d9-b39e-66f157aa8554 # worksコンテンツ画像１枚
    -
      __assoc__:
        -
          - uid
          - fa22373c-b2cb-4021-aaad-b1655ebe3179 # worksスライド画像
    -
      __assoc__:
        -
          - uid
          - ba652aa8-926b-4d56-9c26-c11ad530a796
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
