columnSuffix: null
handle: workContents
instructions: null
name: workコンテンツ
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 61bb92ea-08b8-4743-8609-6d0dd7ae0a9e # 1カラム画像
    -
      __assoc__:
        -
          - uid
          - 87a68457-070e-40c1-bc4f-fdaac0a48fb6 # スライド画像01
    -
      __assoc__:
        -
          - uid
          - cf67f92d-40b1-4976-850f-2913f3d7caba # スライド画像02
    -
      __assoc__:
        -
          - uid
          - 5e53861e-12a5-4222-835e-6bcbb8de1a49 # スライド画像03
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
