columnSuffix: null
handle: workSlideImages
instructions: null
name: workスライド画像
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:0ec3aa91-e4e8-4340-a06a-519f38ee7424' # Work
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 5
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: '{owner.title}'
  restrictedLocationSource: 'volume:0ec3aa91-e4e8-4340-a06a-519f38ee7424' # Work
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
