columnSuffix: null
handle: worksSpace
instructions: null
name: works作業領域
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Planning
        -
          - value
          - Planning
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Web Direction'
        -
          - value
          - 'Web Direction'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Web Design'
        -
          - value
          - 'Web Design'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Web Development'
        -
          - value
          - 'Web Development'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Photograph
        -
          - value
          - Photograph
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Videograph
        -
          - value
          - Videograph
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Graphic Design'
        -
          - value
          - 'Graphic Design'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Copywriting
        -
          - value
          - Copywriting
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Illustration
        -
          - value
          - Illustration
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\MultiSelect
