dateModified: 1742256654
email:
  fromEmail: kaori@cdgrph.com
  fromName: CGtest
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: /uploads
meta:
  __names__:
    0ec3aa91-e4e8-4340-a06a-519f38ee7424: Work # Work
    2a1d939d-8dd8-41f9-ba38-c92b3e2bacb2: works作業領域 # works作業領域
    3a35e34e-277e-47e5-94e8-8f4ff3887ee0: 'Works -Entry' # Works -Entry
    8a6d1f5e-9c85-44b2-a454-d4906858e36c: workTOP画像 # workTOP画像
    60bd9d52-0a9e-439b-8284-74c88ed17eac: workスライド画像 # workスライド画像
    61bb92ea-08b8-4743-8609-6d0dd7ae0a9e: 1カラム画像 # 1カラム画像
    81ba1093-a582-4e79-a6ed-2be54a743712: workクライアント # workクライアント
    87a68457-070e-40c1-bc4f-fdaac0a48fb6: スライド画像 # スライド画像
    414a1587-bd39-4972-9592-f796508591ad: work画像１枚 # work画像１枚
    04546a57-f2f5-462c-93ad-04dba5962df5: work公開年 # work公開年
    bffa93b7-d62e-412f-be4a-661c30b74b33: CGtest # CGtest
    d252e305-bd98-448e-8e02-8e5089425142: workタイトル # workタイトル
    dab1d1ad-6698-4403-a8d7-5eab5fc3ea28: work概要 # work概要
    df661a93-b36d-4097-b71a-954549e12cbb: 'Works Entry' # Works Entry
    e1547157-8cce-47ee-ad7b-ecafd023889a: CGtest # CGtest
    f42b1497-cd88-4002-9a50-77a35f41cc0e: workコンテンツ # workコンテンツ
system:
  edition: solo
  live: true
  name: CGtest
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: Asia/Tokyo
