defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3f9f11ec-2516-48ab-8150-43a411e981cc # Works - Index
handle: worksIndex
maxAuthors: 1
name: 'Works - Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - プライマリのエントリページ
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e1547157-8cce-47ee-ad7b-ecafd023889a: # CGtest
    enabledByDefault: true
    hasUrls: true
    template: works-index/_entry.twig
    uriFormat: works-index
type: single
